---
extends:
  - eslint:recommended
root: true
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2018
rules:
  no-fallthrough: off
  curly: error
  no-else-return: error
  no-inner-declarations: error
  no-unneeded-ternary: error
  no-useless-return: error
  no-console: error
  no-var: error
  one-var:
    - error
    - never
  prefer-arrow-callback: error
  prefer-const: error
  react/no-deprecated: off
  strict: error
  symbol-description: error
  yoda:
    - error
    - never
    - exceptRange: true
overrides:
  - files: "packages/*/test/**/*.js"
    rules:
      strict: off
    globals:
      context: true
      describe: true
      it: true
      before: true
      after: true
