base-build: &base-build
  working_directory: ~/repo
  steps:
    - checkout
    - run: yarn
    - run: yarn run bootstrap
    - run: yarn run ci

version: 2
jobs:
  build-node10:
    docker:
      - image: circleci/node:10
    <<: *base-build

  build-node8:
    docker:
      - image: circleci/node:8
    <<: *base-build

workflows:
  version: 2
  build:
    jobs:
      - build-node10
      - build-node8
